#include "opcodes.h"

#include <map>

static const std::map<uint8_t, OpCode> op_codes = {
    {(uint8_t) 0x69, {0x69, 2, 2, false, "adc", OpCode::AddressingMode::Immediate}},
    {(uint8_t) 0x65, {0x65, 2, 3, false, "adc", OpCode::AddressingMode::ZeroPage}},
    {(uint8_t) 0x75, {0x75, 2, 4, false, "adc", OpCode::AddressingMode::ZeroPageIndexedX}},
    {(uint8_t) 0x6d, {0x6d, 3, 4, false, "adc", OpCode::AddressingMode::Absolute}},
    {(uint8_t) 0x7d, {0x7d, 3, 4, true, "adc", OpCode::AddressingMode::AbsoluteIndexedX}},
    {(uint8_t) 0x79, {0x79, 3, 4, true, "adc", OpCode::AddressingMode::AbsoluteIndexedY}},
    {(uint8_t) 0x61, {0x61, 2, 6, false, "adc", OpCode::AddressingMode::IndirectIndexedX}},
    {(uint8_t) 0x71, {0x71, 2, 5, false, "adc", OpCode::AddressingMode::IndirectIndexedY}},
    {(uint8_t) 0x29, {0x29, 2, 2, false, "and", OpCode::AddressingMode::Immediate}},
    {(uint8_t) 0x25, {0x25, 2, 3, false, "and", OpCode::AddressingMode::ZeroPage}},
    {(uint8_t) 0x35, {0x35, 2, 4, false, "and", OpCode::AddressingMode::ZeroPageIndexedX}},
    {(uint8_t) 0x2d, {0x2d, 3, 4, false, "and", OpCode::AddressingMode::Absolute}},
    {(uint8_t) 0x3d, {0x3d, 3, 4, true, "and", OpCode::AddressingMode::AbsoluteIndexedX}},
    {(uint8_t) 0x39, {0x39, 3, 4, true, "and", OpCode::AddressingMode::AbsoluteIndexedY}},
    {(uint8_t) 0x21, {0x21, 2, 6, false, "and", OpCode::AddressingMode::IndirectIndexedX}},
    {(uint8_t) 0x31, {0x31, 2, 5, false, "and", OpCode::AddressingMode::IndirectIndexedY}},
    {(uint8_t) 0x0a, {0x0a, 1, 2, false, "asl", OpCode::AddressingMode::Accumulator}},
    {(uint8_t) 0x06, {0x06, 2, 5, false, "asl", OpCode::AddressingMode::ZeroPage}},
    {(uint8_t) 0x16, {0x16, 2, 6, false, "asl", OpCode::AddressingMode::ZeroPageIndexedX}},
    {(uint8_t) 0x0e, {0x0e, 3, 6, false, "asl", OpCode::AddressingMode::Absolute}},
    {(uint8_t) 0x1e, {0x1e, 3, 7, false, "asl", OpCode::AddressingMode::AbsoluteIndexedX}},
    {(uint8_t) 0x90, {0x90, 2, 2, true, "bcc", OpCode::AddressingMode::Relative}},
    {(uint8_t) 0xb0, {0xb0, 2, 2, true, "bcs", OpCode::AddressingMode::Relative}},
    {(uint8_t) 0xf0, {0xf0, 2, 2, true, "beq", OpCode::AddressingMode::Relative}},
    {(uint8_t) 0x30, {0x30, 2, 2, true, "bmi", OpCode::AddressingMode::Relative}},
    {(uint8_t) 0xd0, {0xd0, 2, 2, true, "bne", OpCode::AddressingMode::Relative}},
    {(uint8_t) 0x10, {0x10, 2, 2, true, "bpl", OpCode::AddressingMode::Relative}},
    {(uint8_t) 0x50, {0x50, 2, 2, true, "bvc", OpCode::AddressingMode::Relative}},
    {(uint8_t) 0x70, {0x70, 2, 2, true, "bvs", OpCode::AddressingMode::Relative}},
    {(uint8_t) 0x00, {0x00, 1, 7, false, "brk", OpCode::AddressingMode::Implied}},
    {(uint8_t) 0x18, {0x18, 1, 2, false, "clc", OpCode::AddressingMode::Implied}},
    {(uint8_t) 0xd8, {0xd8, 1, 2, false, "cld", OpCode::AddressingMode::Implied}},
    {(uint8_t) 0x58, {0x58, 1, 2, false, "cli", OpCode::AddressingMode::Implied}},
    {(uint8_t) 0xb8, {0xb8, 1, 2, false, "clv", OpCode::AddressingMode::Implied}},
    {(uint8_t) 0x24, {0x24, 2, 3, false, "bit", OpCode::AddressingMode::ZeroPage}},
    {(uint8_t) 0x2c, {0x2c, 3, 4, false, "bit", OpCode::AddressingMode::Absolute}},
    {(uint8_t) 0xc9, {0xc9, 2, 2, false, "cmp", OpCode::AddressingMode::Immediate}},
    {(uint8_t) 0xc5, {0xc5, 2, 3, false, "cmp", OpCode::AddressingMode::ZeroPage}},
    {(uint8_t) 0xd5, {0xd5, 2, 4, false, "cmp", OpCode::AddressingMode::ZeroPageIndexedX}},
    {(uint8_t) 0xcd, {0xcd, 3, 4, false, "cmp", OpCode::AddressingMode::Absolute}},
    {(uint8_t) 0xdd, {0xdd, 3, 4, true, "cmp", OpCode::AddressingMode::AbsoluteIndexedX}},
    {(uint8_t) 0xd9, {0xd9, 3, 4, true, "cmp", OpCode::AddressingMode::AbsoluteIndexedY}},
    {(uint8_t) 0xc1, {0xc1, 2, 6, false, "cmp", OpCode::AddressingMode::IndirectIndexedX}},
    {(uint8_t) 0xd1, {0xd1, 2, 5, false, "cmp", OpCode::AddressingMode::IndirectIndexedY}},
    {(uint8_t) 0xe0, {0xe0, 2, 2, false, "cpx", OpCode::AddressingMode::Immediate}},
    {(uint8_t) 0xe4, {0xe4, 2, 3, false, "cpx", OpCode::AddressingMode::ZeroPage}},
    {(uint8_t) 0xec, {0xec, 3, 4, false, "cpx", OpCode::AddressingMode::Absolute}},
    {(uint8_t) 0xc0, {0xc0, 2, 2, false, "cpy", OpCode::AddressingMode::Immediate}},
    {(uint8_t) 0xc4, {0xc4, 2, 3, false, "cpy", OpCode::AddressingMode::ZeroPage}},
    {(uint8_t) 0xcc, {0xcc, 3, 4, false, "cpy", OpCode::AddressingMode::Absolute}},
    {(uint8_t) 0xc6, {0xc6, 2, 5, false, "dec", OpCode::AddressingMode::ZeroPage}},
    {(uint8_t) 0xd6, {0xd6, 2, 6, false, "dec", OpCode::AddressingMode::ZeroPageIndexedX}},
    {(uint8_t) 0xce, {0xce, 3, 6, false, "dec", OpCode::AddressingMode::Absolute}},
    {(uint8_t) 0xde, {0xde, 3, 7, false, "dec", OpCode::AddressingMode::AbsoluteIndexedX}},
    {(uint8_t) 0xca, {0xca, 1, 2, false, "dex", OpCode::AddressingMode::Implied}},
    {(uint8_t) 0x88, {0x88, 1, 2, false, "dey", OpCode::AddressingMode::Implied}},
    {(uint8_t) 0x49, {0x49, 2, 2, false, "eor", OpCode::AddressingMode::Immediate}},
    {(uint8_t) 0x45, {0x45, 2, 3, false, "eor", OpCode::AddressingMode::ZeroPage}},
    {(uint8_t) 0x55, {0x55, 2, 4, false, "eor", OpCode::AddressingMode::ZeroPageIndexedX}},
    {(uint8_t) 0x4d, {0x4d, 3, 4, false, "eor", OpCode::AddressingMode::Absolute}},
    {(uint8_t) 0x5d, {0x5d, 3, 4, true, "eor", OpCode::AddressingMode::AbsoluteIndexedX}},
    {(uint8_t) 0x59, {0x59, 3, 4, true, "eor", OpCode::AddressingMode::AbsoluteIndexedY}},
    {(uint8_t) 0x41, {0x41, 2, 6, false, "eor", OpCode::AddressingMode::IndirectIndexedX}},
    {(uint8_t) 0x51, {0x51, 2, 5, true, "eor", OpCode::AddressingMode::IndirectIndexedY}},
    {(uint8_t) 0xe6, {0xe6, 2, 5, false, "inc", OpCode::AddressingMode::ZeroPage}},
    {(uint8_t) 0xf6, {0xf6, 2, 6, false, "inc", OpCode::AddressingMode::ZeroPageIndexedX}},
    {(uint8_t) 0xee, {0xee, 3, 6, false, "inc", OpCode::AddressingMode::Absolute}},
    {(uint8_t) 0xfe, {0xfe, 3, 7, false, "inc", OpCode::AddressingMode::AbsoluteIndexedX}},
    {(uint8_t) 0xe8, {0xe8, 1, 2, false, "inx", OpCode::AddressingMode::Implied}},
    {(uint8_t) 0xc8, {0xc8, 1, 2, false, "iny", OpCode::AddressingMode::Implied}},
    {(uint8_t) 0x4c, {0x4c, 3, 3, false, "jmp", OpCode::AddressingMode::Absolute}},
    {(uint8_t) 0x6c, {0x6c, 3, 5, false, "jmp", OpCode::AddressingMode::Indirect}},
    {(uint8_t) 0x20, {0x20, 3, 6, false, "jsr", OpCode::AddressingMode::Absolute}},
    {(uint8_t) 0xa5, {0xa5, 2, 2, false, "lda", OpCode::AddressingMode::ZeroPage}},
    {(uint8_t) 0xa9, {0xa9, 2, 3, false, "lda", OpCode::AddressingMode::Immediate}},
    {(uint8_t) 0xad, {0xad, 3, 4, false, "lda", OpCode::AddressingMode::Absolute}},
    {(uint8_t) 0xb5, {0xb5, 3, 4, false, "lda", OpCode::AddressingMode::ZeroPageIndexedX}},
    {(uint8_t) 0xb9, {0xb9, 3, 4, true, "lda", OpCode::AddressingMode::AbsoluteIndexedY}},
    {(uint8_t) 0xbd, {0xbd, 3, 4, true, "lda", OpCode::AddressingMode::AbsoluteIndexedX}},
    {(uint8_t) 0xa1, {0xa1, 2, 6, false, "lda", OpCode::AddressingMode::IndirectIndexedX}},
    {(uint8_t) 0xb1, {0xb1, 2, 5, true, "lda", OpCode::AddressingMode::IndirectIndexedY}},
    {(uint8_t) 0xa2, {0xa2, 2, 2, false, "ldx", OpCode::AddressingMode::Immediate}},
    {(uint8_t) 0xa6, {0xa6, 2, 3, false, "ldx", OpCode::AddressingMode::ZeroPage}},
    {(uint8_t) 0xb6, {0xb6, 2, 4, false, "ldx", OpCode::AddressingMode::ZeroPageIndexedY}},
    {(uint8_t) 0xae, {0xae, 3, 4, false, "ldx", OpCode::AddressingMode::Absolute}},
    {(uint8_t) 0xbe, {0xbe, 3, 4, true, "ldx", OpCode::AddressingMode::AbsoluteIndexedY}},
    {(uint8_t) 0xa0, {0xa0, 2, 2, false, "ldy", OpCode::AddressingMode::Immediate}},
    {(uint8_t) 0xa4, {0xa4, 2, 3, false, "ldy", OpCode::AddressingMode::ZeroPage}},
    {(uint8_t) 0xb4, {0xb4, 2, 4, false, "ldy", OpCode::AddressingMode::ZeroPageIndexedX}},
    {(uint8_t) 0xac, {0xac, 3, 4, false, "ldy", OpCode::AddressingMode::Absolute}},
    {(uint8_t) 0xbc, {0xbc, 3, 4, true, "ldy", OpCode::AddressingMode::AbsoluteIndexedX}},
    {(uint8_t) 0x4a, {0x4a, 1, 2, false, "lsr", OpCode::AddressingMode::Accumulator}},
    {(uint8_t) 0x46, {0x46, 2, 5, false, "lsr", OpCode::AddressingMode::ZeroPage}},
    {(uint8_t) 0x56, {0x56, 2, 6, false, "lsr", OpCode::AddressingMode::ZeroPageIndexedX}},
    {(uint8_t) 0x4e, {0x4e, 3, 6, false, "lsr", OpCode::AddressingMode::Absolute}},
    {(uint8_t) 0x5e, {0x5e, 3, 7, false, "lsr", OpCode::AddressingMode::AbsoluteIndexedX}},
    {(uint8_t) 0xea, {0xea, 1, 2, false, "nop", OpCode::AddressingMode::Implied}},
    {(uint8_t) 0x09, {0x09, 2, 2, false, "ora", OpCode::AddressingMode::Immediate}},
    {(uint8_t) 0x05, {0x05, 2, 3, false, "ora", OpCode::AddressingMode::ZeroPage}},
    {(uint8_t) 0x15, {0x15, 2, 4, false, "ora", OpCode::AddressingMode::ZeroPageIndexedX}},
    {(uint8_t) 0x0d, {0x0d, 3, 4, false, "ora", OpCode::AddressingMode::Absolute}},
    {(uint8_t) 0x1d, {0x1d, 3, 4, true, "ora", OpCode::AddressingMode::AbsoluteIndexedX}},
    {(uint8_t) 0x19, {0x19, 3, 4, true, "ora", OpCode::AddressingMode::AbsoluteIndexedY}},
    {(uint8_t) 0x01, {0x01, 2, 6, false, "ora", OpCode::AddressingMode::IndirectIndexedX}},
    {(uint8_t) 0x11, {0x11, 2, 5, true, "ora", OpCode::AddressingMode::IndirectIndexedY}},
    {(uint8_t) 0x48, {0x48, 1, 3, false, "pha", OpCode::AddressingMode::Implied}},
    {(uint8_t) 0x08, {0x08, 1, 3, false, "php", OpCode::AddressingMode::Implied}},
    {(uint8_t) 0x68, {0x68, 1, 4, false, "pla", OpCode::AddressingMode::Implied}},
    {(uint8_t) 0x28, {0x28, 1, 4, false, "plp", OpCode::AddressingMode::Implied}},
    {(uint8_t) 0x2a, {0x2a, 1, 2, false, "rol", OpCode::AddressingMode::Accumulator}},
    {(uint8_t) 0x26, {0x26, 2, 5, false, "rol", OpCode::AddressingMode::ZeroPage}},
    {(uint8_t) 0x36, {0x36, 2, 6, false, "rol", OpCode::AddressingMode::ZeroPageIndexedX}},
    {(uint8_t) 0x2e, {0x2e, 3, 6, false, "rol", OpCode::AddressingMode::Absolute}},
    {(uint8_t) 0x3e, {0x3e, 3, 7, false, "rol", OpCode::AddressingMode::AbsoluteIndexedX}},
    {(uint8_t) 0x6a, {0x6a, 1, 2, false, "ror", OpCode::AddressingMode::Accumulator}},
    {(uint8_t) 0x66, {0x66, 2, 5, false, "ror", OpCode::AddressingMode::ZeroPage}},
    {(uint8_t) 0x76, {0x76, 2, 6, false, "ror", OpCode::AddressingMode::ZeroPageIndexedX}},
    {(uint8_t) 0x6e, {0x6e, 3, 6, false, "ror", OpCode::AddressingMode::Absolute}},
    {(uint8_t) 0x7e, {0x7e, 3, 7, false, "ror", OpCode::AddressingMode::AbsoluteIndexedX}},
    {(uint8_t) 0x40, {0x40, 1, 6, false, "rti", OpCode::AddressingMode::Implied}},
    {(uint8_t) 0x60, {0x60, 1, 6, false, "rts", OpCode::AddressingMode::Implied}},
    {(uint8_t) 0xe9, {0xe9, 2, 2, false, "sbc", OpCode::AddressingMode::Immediate}},
    {(uint8_t) 0xe5, {0xe5, 2, 3, false, "sbc", OpCode::AddressingMode::ZeroPage}},
    {(uint8_t) 0xf5, {0xf5, 2, 4, false, "sbc", OpCode::AddressingMode::ZeroPageIndexedX}},
    {(uint8_t) 0xed, {0xed, 3, 4, false, "sbc", OpCode::AddressingMode::Absolute}},
    {(uint8_t) 0xfd, {0xfd, 3, 4, true, "sbc", OpCode::AddressingMode::AbsoluteIndexedX}},
    {(uint8_t) 0xf9, {0xf9, 3, 4, true, "sbc", OpCode::AddressingMode::AbsoluteIndexedY}},
    {(uint8_t) 0xe1, {0xe1, 2, 6, false, "sbc", OpCode::AddressingMode::IndirectIndexedX}},
    {(uint8_t) 0xf1, {0xf1, 2, 5, true, "sbc", OpCode::AddressingMode::IndirectIndexedY}},
    {(uint8_t) 0x38, {0x38, 1, 2, false, "sec", OpCode::AddressingMode::Implied}},
    {(uint8_t) 0xf8, {0xf8, 1, 2, false, "sed", OpCode::AddressingMode::Implied}},
    {(uint8_t) 0x78, {0x78, 1, 2, false, "sei", OpCode::AddressingMode::Implied}},
    {(uint8_t) 0x85, {0x85, 2, 3, false, "sta", OpCode::AddressingMode::ZeroPage}},
    {(uint8_t) 0x95, {0x95, 2, 4, false, "sta", OpCode::AddressingMode::ZeroPageIndexedX}},
    {(uint8_t) 0x8d, {0x8d, 3, 4, false, "sta", OpCode::AddressingMode::Absolute}},
    {(uint8_t) 0x9d, {0x9d, 3, 5, false, "sta", OpCode::AddressingMode::AbsoluteIndexedX}},
    {(uint8_t) 0x99, {0x99, 3, 5, false, "sta", OpCode::AddressingMode::AbsoluteIndexedY}},
    {(uint8_t) 0x81, {0x81, 2, 6, false, "sta", OpCode::AddressingMode::IndirectIndexedX}},
    {(uint8_t) 0x91, {0x91, 2, 6, false, "sta", OpCode::AddressingMode::IndirectIndexedY}},
    {(uint8_t) 0x86, {0x86, 2, 3, false, "stx", OpCode::AddressingMode::ZeroPage}},
    {(uint8_t) 0x96, {0x96, 2, 4, false, "stx", OpCode::AddressingMode::ZeroPageIndexedY}},
    {(uint8_t) 0x8e, {0x8e, 3, 4, false, "stx", OpCode::AddressingMode::Absolute}},
    {(uint8_t) 0x84, {0x84, 2, 3, false, "sty", OpCode::AddressingMode::ZeroPage}},
    {(uint8_t) 0x94, {0x94, 2, 4, false, "sty", OpCode::AddressingMode::ZeroPageIndexedX}},
    {(uint8_t) 0x8c, {0x8c, 3, 4, false, "sty", OpCode::AddressingMode::Absolute}},
    {(uint8_t) 0xaa, {0xaa, 1, 2, false, "tax", OpCode::AddressingMode::Implied}},
    {(uint8_t) 0xa8, {0xa8, 1, 2, false, "tay", OpCode::AddressingMode::Implied}},
    {(uint8_t) 0xba, {0xba, 1, 2, false, "tsx", OpCode::AddressingMode::Implied}},
    {(uint8_t) 0x8a, {0x8a, 1, 2, false, "txa", OpCode::AddressingMode::Implied}},
    {(uint8_t) 0x9a, {0x9a, 1, 2, false, "txs", OpCode::AddressingMode::Implied}},
    {(uint8_t) 0x98, {0x98, 1, 2, false, "tya", OpCode::AddressingMode::Implied}},
};


OpCode OpCode::for_value(uint8_t value) {
  auto iter = op_codes.find(value);
  if (iter == op_codes.end()) {
    return OpCode::unknown_opcode;
  }
  return iter->second;
}

const OpCode OpCode::unknown_opcode{0xff, 1, 2, false, "???", OpCode::Implied};
